"""Mock stub generated by Tool Discoverer for compare_measurement_groups."""

from __future__ import annotations


def compare_measurement_groups(
    group_a: list,
    group_b: list,
    test_type: str | None = None,
    alpha_level: float | None = None,
) -> dict:
    """Perform statistical comparison between two groups of measurements to assess differences in their means or distributions. Use this tool when you have two sets of numerical data and want to determine if they are statistically significantly different. Do NOT use this tool for comparing more than two groups (use 'compare_multiple_groups' for that) or for non-numerical data.

    Args:
        group_a: First group of measurements, represented as an array of numbers. Each measurement must be a finite number. The group must contain at least 2 measurements.
        group_b: Second group of measurements, represented as an array of numbers. Each measurement must be a finite number. The group must contain at least 2 measurements.
        test_type: Type of statistical test to perform. Must be one of: 't-test' for comparing means or 'mann-whitney' for comparing distributions. Defaults to 't-test' if not specified.
        alpha_level: Significance level for the statistical test, as a decimal (e.g. 0.05 for 5% significance). Must be between 0 and 1. Defaults to 0.05 if not specified.

    Returns:
        Results of the statistical comparison including p-value, test statistic, and significance indication.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
