"""Mock stub generated by Tool Discoverer for compute_bmi."""

from __future__ import annotations


def compute_bmi(
    weight_kg: float,
    height_m: float,
) -> dict:
    """Calculate the Body Mass Index (BMI) based on a person's weight in kilograms and height in meters. Use this tool when you need to assess whether an individual has a healthy body weight relative to their height. Do NOT use this tool for other health assessments or calculations unrelated to BMI.

    Args:
        weight_kg: The weight of the person in kilograms. Must be a positive number greater than 0. For example, 70.5.
        height_m: The height of the person in meters. Must be a positive number greater than 0. For example, 1.75.

    Returns:
        Object containing the calculated BMI value and the corresponding weight category.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
