"""Mock stub generated by Tool Discoverer for compute_bmi."""

from __future__ import annotations


def compute_bmi(
    weight_kg: float,
    height_m: float,
) -> dict:
    """Calculate the Body Mass Index (BMI) based on a person's weight and height. Use this tool when you need to determine if someone is underweight, normal weight, overweight, or obese according to BMI classifications. Do NOT use this tool for individuals with atypical body compositions (e.g., athletes with high muscle mass) or for medical diagnoses; consult a healthcare professional for such cases.

    Args:
        weight_kg: The weight of the individual in kilograms. Must be a positive number greater than 0. For example, 70.5.
        height_m: The height of the individual in meters. Must be a positive number greater than 0. For example, 1.75.

    Returns:
        Object containing the calculated BMI value and the corresponding weight category.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
