"""Mock stub generated by Tool Discoverer for convert_dna_to_rna."""

from __future__ import annotations


def convert_dna_to_rna(
    dna_sequence: str,
) -> dict:
    """Convert a DNA sequence into its corresponding RNA sequence by replacing thymine (T) with uracil (U). Use this tool when you have a DNA sequence that you need to transcribe into RNA. Do NOT use this tool for sequences that are already RNA or for other types of biological transformations (e.g., protein synthesis).

    Args:
        dna_sequence: The DNA sequence to convert, represented as a string of nucleotide codes (A, T, C, G). Must not contain any whitespace, line breaks, or invalid characters. Length must be between 1 and 10,000 characters.

    Returns:
        Object containing the converted RNA sequence.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
