"""Mock stub generated by Tool Discoverer for convert_dna_to_rna."""

from __future__ import annotations


def convert_dna_to_rna(
    dna_sequence: str,
) -> dict:
    """Convert a DNA sequence to its corresponding RNA sequence by transcribing thymine (T) to uracil (U). Use this tool when you need to transcribe a DNA sequence for RNA analysis or synthesis. Do NOT use this tool for sequences that are not DNA (e.g., RNA or protein sequences) or for tasks requiring more complex manipulations (e.g., reverse transcription).

    Args:
        dna_sequence: The DNA sequence to be converted, represented as a string of nucleotide codes (A, T, C, G). Must not contain whitespace, line breaks, or any characters other than A, T, C, G. Length must be between 1 and 10,000 characters.

    Returns:
        Object containing the transcribed RNA sequence.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
