"""Mock stub generated by Tool Discoverer for get_ncbi_gene_info."""

from __future__ import annotations


def get_ncbi_gene_info(
    gene_symbol: str,
    include_function: bool | None = None,
) -> dict:
    """Look up gene information from the NCBI Entrez database using the official HGNC gene symbol (e.g. 'BRCA1', 'TP53'). Returns details such as gene name, organism, chromosome location, and function. Use this tool when you have a specific HGNC gene symbol. Do NOT use this tool for non-HGNC identifiers or for searching by gene name; use 'search_ncbi_by_name' for broader queries.

    Args:
        gene_symbol: The official HGNC gene symbol, a string of uppercase letters (e.g. 'BRCA1'). Must be a valid HGNC symbol; the function raises an error if not found.
        include_function: Whether to include a description of the gene's biological function in the response. Set to false to reduce response size if only basic metadata is needed. Defaults to true.

    Returns:
        Gene metadata including symbol, name, organism, chromosome location, and optional function description.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
