"""Mock stub generated by Tool Discoverer for get_gene_info."""

from __future__ import annotations


def get_gene_info(
    gene_symbol: str,
    include_pathways: bool | None = None,
) -> dict:
    """Fetch detailed information about a specific gene using its gene symbol. Returns the gene's name, organism, function, and associated pathways. Use this tool when you have a specific gene symbol (e.g. 'TP53'). Do NOT use this tool for searching genes by other criteria (e.g. gene ID or keyword); use 'search_genes_by_criteria' for that.

    Args:
        gene_symbol: The official gene symbol representing the gene of interest, typically consisting of uppercase letters (e.g. 'TP53'). Must be a valid gene symbol recognized in the relevant database.
        include_pathways: Whether to include associated biological pathways in the response. Set to false to reduce response size if pathways are not needed. Defaults to true.

    Returns:
        Gene metadata including symbol, name, organism, function, and optional pathways.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
