"""Mock stub generated by Tool Discoverer for get_rcsb_pdb_metadata."""

from __future__ import annotations


def get_rcsb_pdb_metadata(
    pdb_id: str,
    include_chain_composition: bool | None = None,
) -> dict:
    """Retrieve 3D structure metadata for a protein from the RCSB Protein Data Bank using a 4-character PDB ID. Returns information such as resolution, experimental method, and chain composition. Use this tool when you have a specific PDB ID (e.g. '1A0A'). Do NOT use this tool for searching or querying by other identifiers; use 'search_rcsb_pdb' for broader queries.

    Args:
        pdb_id: The 4-character PDB ID representing the protein structure (e.g. '1A0A'). Must be exactly 4 characters long and alphanumeric. The function raises an error if the ID is invalid or not found.
        include_chain_composition: Whether to include detailed chain composition in the response. Set to false to reduce response size if only resolution and method are needed. Defaults to true.

    Returns:
        Metadata including PDB ID, resolution, experimental method, and optional chain composition.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
