"""Mock stub generated by Tool Discoverer for search_pubmed."""

from __future__ import annotations


def search_pubmed(
    query: str,
    max_results: int | None = None,
    min_year: int | None = None,
) -> dict:
    """Search the PubMed biomedical literature database for articles matching a free-text query. Use this tool when the user asks to find scientific papers, literature reviews, or evidence on a biomedical topic. Do NOT use for non-biomedical literature (e.g. CS papers — use arXiv tools instead).

    Args:
        query: Free-text search query using PubMed query syntax. Supports Boolean operators (AND, OR, NOT) and MeSH terms. Example: 'BRCA1 AND breast cancer AND (therapy OR treatment)'. Should be a complete query string, not just keywords.
        max_results: Maximum number of articles to return, ranked by PubMed relevance score. Must be between 1 and 100. Defaults to 20 if not specified.
        min_year: Earliest publication year to include (inclusive), as a 4-digit year e.g. 2020. Articles published before this year are excluded. Omit to include all years.

    Returns:
        Object with 'articles' (list of metadata) and 'total_count' (total matches before truncation).
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
