"""Mock stub generated by Tool Discoverer for search_clinical_trials."""

from __future__ import annotations


def search_clinical_trials(
    condition: str,
    max_results: int | None = None,
    status: str | None = None,
) -> dict:
    """Search ClinicalTrials.gov for clinical trials related to a specific medical condition. Returns trial IDs, titles, and recruitment status. Use this tool when you need information about ongoing or completed clinical trials for a particular condition. Do NOT use this tool for non-clinical trial data or for searching other databases; use 'search_pubmed' for literature searches instead.

    Args:
        condition: The medical condition to search for in clinical trials, represented as a free-text string. Should be specific enough to yield relevant results (e.g. 'diabetes', 'breast cancer').
        max_results: Maximum number of trials to return, must be between 1 and 100. Defaults to 20 if not specified.
        status: Filter results by recruitment status. Must be one of: 'Recruiting', 'Not yet recruiting', 'Completed', 'Terminated', 'Suspended', 'Withdrawn'. If omitted, all statuses are included.

    Returns:
        Object containing 'trials' (list of trial metadata) and 'total_count' (total matches before truncation).
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
