"""Mock stub generated by Tool Discoverer for search_pubmed_articles."""

from __future__ import annotations


def search_pubmed_articles(
    query: str,
    min_year: int | None = None,
    max_year: int | None = None,
    journal_name: str | None = None,
    author_last_name: str | None = None,
    max_results: int | None = None,
) -> dict:
    """Search PubMed for biomedical articles based on a free-text query with optional filters for publication year range, journal name, and author last name. Use this tool when the user requests to find scientific papers or literature on a biomedical topic. Do NOT use for non-biomedical literature (e.g. CS papers — use arXiv tools instead).

    Args:
        query: Free-text search query using PubMed query syntax. Supports Boolean operators (AND, OR, NOT) and MeSH terms. Example: 'cancer AND therapy'. Should be a complete query string, not just keywords.
        min_year: Earliest publication year to include (inclusive), as a 4-digit year (e.g. 2020). Articles published before this year are excluded. Omit to include all years.
        max_year: Latest publication year to include (inclusive), as a 4-digit year (e.g. 2023). Articles published after this year are excluded. Omit to include all years.
        journal_name: Name of the journal to filter results by. Should match the journal title as indexed in PubMed. Omit to include articles from all journals.
        author_last_name: Last name of the author to filter results by. Should match the author's last name as indexed in PubMed. Omit to include articles by all authors.
        max_results: Maximum number of articles to return, ranked by PubMed relevance score. Must be between 1 and 100. Defaults to 20 if not specified.

    Returns:
        Object with 'articles' (list of metadata) and 'total_count' (total matches before truncation).
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
