"""Mock stub generated by Tool Discoverer for convert_gene_symbol_to_ensembl_id."""

from __future__ import annotations


def convert_gene_symbol_to_ensembl_id(
    gene_symbol: str,
) -> dict:
    """Convert a gene symbol to its corresponding Ensembl gene ID. Use this tool when you have a specific gene symbol (e.g. 'TP53') and need to find its Ensembl ID. Do NOT use this tool for non-standard gene symbols or for retrieving information about multiple genes at once; for batch queries, consider using 'convert_multiple_gene_symbols'.

    Args:
        gene_symbol: The official gene symbol for which to retrieve the Ensembl gene ID. Must be a valid gene symbol recognized by Ensembl (e.g. 'TP53'). Case-insensitive.

    Returns:
        Object containing the input gene symbol, the corresponding Ensembl gene ID, and the status of the conversion.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
