"""Mock stub generated by Tool Discoverer for fetch_pubmed_abstract."""

from __future__ import annotations


def fetch_pubmed_abstract(
    pmid: str,
) -> dict:
    """Fetch the abstract of a PubMed article given its PMID (PubMed Identifier). Use this tool when you have a valid PMID and need to retrieve the abstract of the corresponding article. Do NOT use this tool for articles without a PMID or for retrieving other types of metadata (e.g., title, authors) — use 'get_pubmed_article_metadata' for that.

    Args:
        pmid: The PubMed Identifier (PMID) for the article, a unique 8-digit number (e.g., '12345678'). Must be a valid PMID; the function raises an error if not found.

    Returns:
        Object containing the abstract of the requested PubMed article.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
