"""Mock stub generated by Tool Discoverer for get_protein_tissue_expression."""

from __future__ import annotations


def get_protein_tissue_expression(
    gene_name: str,
    include_normal_tissues: bool | None = None,
    include_disease_tissues: bool | None = None,
) -> dict:
    """Retrieve protein tissue expression information based on a given gene name. Use this tool when you need to find out where a specific protein is expressed in different tissues. Do NOT use this tool for retrieving general protein information or sequence data; for that, use 'get_uniprot_protein_info'.

    Args:
        gene_name: The official gene symbol for the protein of interest, following standard nomenclature (e.g. 'TP53'). Must be a valid gene name recognized in the relevant databases.
        include_normal_tissues: Whether to include expression data from normal tissues. Set to true to get a comprehensive view of expression across normal tissues. Defaults to true.
        include_disease_tissues: Whether to include expression data from diseased tissues. Set to true to include this data. Defaults to false.

    Returns:
        Object containing the gene name, tissue expression data, and flags indicating which types of tissues were included.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
