"""Mock stub generated by Tool Discoverer for get_drug_side_effects."""

from __future__ import annotations


def get_drug_side_effects(
    drug_name: str,
    include_common_side_effects: bool | None = None,
    include_rare_side_effects: bool | None = None,
) -> dict:
    """Fetch known side effects of a specified drug by its name. Use this tool when you need to obtain information about the adverse effects associated with a particular medication. Do NOT use this tool for off-label uses or to obtain information about drug interactions; for that, consider using 'get_drug_interactions'.

    Args:
        drug_name: The name of the drug for which to retrieve side effects. Must be a valid drug name as recognized in medical databases. Should not include dosage forms or additional descriptors.
        include_common_side_effects: Whether to include common side effects in the response. Set to true to receive a comprehensive list including common effects. Defaults to true.
        include_rare_side_effects: Whether to include rare side effects in the response. Set to true to receive a complete list including rare effects. Defaults to false.

    Returns:
        Object containing the drug name and lists of common and rare side effects based on user preferences.
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
